// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/little-princess/Current.tsx": () => import("../components/mockups/little-princess/Current.tsx"),
  "./components/mockups/little-princess/Premium.tsx": () => import("../components/mockups/little-princess/Premium.tsx")
};
